# Generated by Django 4.0.1 on 2022-01-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0003_item_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='total_price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
