# Generated by Django 4.0.1 on 2022-02-04 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0006_remove_order_worker_order_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_no',
        ),
    ]
