# Generated by Django 4.0.1 on 2022-02-06 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0010_order_order_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_no',
            field=models.CharField(max_length=100),
        ),
    ]
