# Generated by Django 4.0.1 on 2022-02-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0012_remove_order_created_at_order_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.CharField(default='13', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='23:09:18', max_length=10),
        ),
    ]
