# Generated by Django 4.0.1 on 2022-03-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0013_order_owner_name_alter_order_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.CharField(default='06', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_month',
            field=models.CharField(default='03', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='07:04:23', max_length=10),
        ),
    ]
