# Generated by Django 4.0.1 on 2022-03-06 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0014_alter_order_created_date_alter_order_created_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='07:17:53', max_length=10),
        ),
    ]
