# Generated by Django 4.0.1 on 2022-03-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0016_alter_order_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.CharField(default='07', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='00:21:19', max_length=10),
        ),
    ]
