# Generated by Django 4.0.1 on 2022-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0019_alter_order_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.CharField(default='20', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='06:24:44', max_length=10),
        ),
        migrations.AlterModelTable(
            name='order',
            table='b1_orders_order',
        ),
    ]
