# Generated by Django 4.0.1 on 2022-03-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0020_alter_order_created_date_alter_order_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='22:15:15', max_length=10),
        ),
    ]
