# Generated by Django 4.0.1 on 2022-03-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0021_alter_order_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.CharField(default='21', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='00:46:29', max_length=10),
        ),
    ]
