# Generated by Django 4.0.1 on 2022-03-21 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B1_orders', '0022_alter_order_created_date_alter_order_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_time',
            field=models.CharField(default='08:12:17', max_length=10),
        ),
    ]
