# Generated by Django 4.0.1 on 2022-01-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='FOOD', max_length=100)),
                ('type', models.CharField(default='Bread', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('extras', models.JSONField(null=True)),
                ('sizes_prices', models.JSONField(null=True)),
                ('img', models.ImageField(default='static/images/addimage123.png', upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='BEVERAGE', max_length=100)),
                ('type', models.CharField(default='Coffee', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('extras', models.JSONField(null=True)),
                ('sizes_prices', models.JSONField(null=True)),
                ('img', models.ImageField(default='static/images/addimage123.png', upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='FOOD', max_length=100)),
                ('type', models.CharField(default='Ice cream', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('extras', models.JSONField(null=True)),
                ('sizes_prices', models.JSONField(null=True)),
                ('img', models.ImageField(default='static/images/addimage123.png', upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Juice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='BEVERAGE', max_length=100)),
                ('type', models.CharField(default='Juice', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('extras', models.JSONField(null=True)),
                ('sizes_prices', models.JSONField(null=True)),
                ('img', models.ImageField(default='static/images/addimage123.png', upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='MilkTea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='BEVERAGE', max_length=100)),
                ('type', models.CharField(default='Milk Tea', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('extras', models.JSONField(null=True)),
                ('sizes_prices', models.JSONField(null=True)),
                ('img', models.ImageField(default='static/images/addimage123.png', upload_to='static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Others',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='BEVERAGE', max_length=100)),
                ('type', models.CharField(default='Others', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('extras', models.JSONField(null=True)),
                ('sizes_prices', models.JSONField(null=True)),
                ('img', models.ImageField(default='static/images/addimage123.png', upload_to='static/images/')),
            ],
        ),
    ]
