# Generated by Django 4.0.1 on 2022-01-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2_menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Others',
            new_name='Other',
        ),
    ]
