# Generated by Django 4.0.1 on 2022-01-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B2_menu', '0002_rename_others_other'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Other',
            new_name='Item',
        ),
        migrations.DeleteModel(
            name='Bread',
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='IceCream',
        ),
        migrations.DeleteModel(
            name='Juice',
        ),
        migrations.DeleteModel(
            name='MilkTea',
        ),
    ]
