# Generated by Django 4.0.1 on 2022-02-02 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2_menu', '0004_alter_item_category_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]
