# Generated by Django 4.0.1 on 2022-02-13 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('B2_menu', '0005_alter_item_category_alter_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='img',
            field=models.ImageField(default='static/images/addimage.png', upload_to='static/images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
