export const actionTypes = {
    MENU_MADE: 'MENU_MADE',
    GET_MEDIUM_ITEM: 'GET_MEDIUM_ITEM',     //for setting a new order
    
    ITEM_SET: 'ITEM_SET',
    ITEM_CANCELLED: 'ITEM_CANCELLED',
    ITEMS_PAID: 'ITEMS_PAID',
    ORDER_SAVED: 'ORDER_SAVED', 

    //MESSAGE AND ERRORS:
    GET_ERRORS: 'GET_ERRORS',
    CREATE_MESSAGE: 'CREATE_MESSAGE',

    //Worker:
    LOGIN_SUCCEED: "LOGIN_SUCCEED",
    LOGIN_FAILED: "LOGIN_FAILED",
    LOG_OUT_SUCCEED: "LOG_OUT_SUCCEED",
    //Update Profile: change password
    PASSWORD_CHANGED_SUCCEED: "PASSWORD_CHANGED_SUCCEED",
    PASSWORD_CHANGED_FAILED: "PASSWORD_CHANGED_FAILED",

    //Calling Token:
    USER_LOADING: "USER_LOADING",
    USER_LOADED_SUCCESS: "USER_LOADED_SUCCESS",
    TOKEN_DEAD: "TOKEN_DEAD",

    //Register:
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAILED: "REGISTER_FAILED",

    //SALES:
    SALES_ORDERS: "SALES_ORDERS",
    ORDER_NO_GET: 'ORDER_NO_GET',

    //Add new item into Menu
    NEW_ITEM_ADDED: 'NEW_ITEM_ADDED',       //add new item into a menu 
    NEW_ITEM_KEPT: 'NEW_ITEM_KEPT',
    ITEM_DELETED: 'ITEM_DELETED',
    
    NEW_ITEM_ADDED_OK: "NEW_ITEM_ADDED_OK",
    NEW_ITEM_ADDED_FAILED: "NEW_ITEM_ADDED_FAILED",
    ITEM_UPDATED: "ITEM_UPDATED",
    ITEM_UPDATED_SUCCESS: "ITEM_UPDATED_SUCCESS",
    

    //Get videos out
    VIDEO_GET: 'VIDEO_GET',
    DOUBLE_DB_VIDEO_GET: 'DOUBLE_DB_VIDEO_GET',

    //plotting
    PANDAS_GET: "PANDAS_GET",
}