# Generated by Django 4.0.1 on 2022-03-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='video', max_length=100, null=True)),
                ('content', models.FileField(default='static/videos/Dragostea.mp3', upload_to='static/videos/')),
            ],
        ),
    ]
