# Generated by Django 4.0.1 on 2022-03-07 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('D_videos', '0002_video_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='video', max_length=100, null=True)),
                ('content', models.FileField(default='static/videos/Dragostea.mp3', upload_to='static/videos/')),
                ('comment', models.CharField(default='idea', max_length=1000, null=True)),
            ],
        ),
    ]
