# Generated by Django 4.0.1 on 2022-01-24 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('B_workers', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
